spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1029519495252-6ncvhc3ba5327rpsbbfkj3rerpo3lkij.apps.googleusercontent.com
            client-secret: i9B3zZTcWZNTetPM626RFUs7
            scope:
              - email
              - profile